<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '1608f0a4dbb710c7b1d821147427c564',
  'DATABASE_URL' => 'mysql://c1_maty:sqnXxQJVq2!X@vardump.eu/c1_maty',
);
