<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5JcuXnl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5JcuXnl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5JcuXnl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5JcuXnl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5JcuXnl\App_KernelDevDebugContainer([
    'container.build_hash' => '5JcuXnl',
    'container.build_id' => '11071957',
    'container.build_time' => 1676279372,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5JcuXnl');
