<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHt7xDkJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHt7xDkJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHt7xDkJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHt7xDkJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHt7xDkJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ht7xDkJ',
    'container.build_id' => '990ccdad',
    'container.build_time' => 1676445821,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHt7xDkJ');
