<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUPs9p4d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUPs9p4d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUPs9p4d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUPs9p4d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUPs9p4d\App_KernelDevDebugContainer([
    'container.build_hash' => 'UPs9p4d',
    'container.build_id' => 'e7bdbe92',
    'container.build_time' => 1675625241,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUPs9p4d');
