<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\HomePageController::homepage'], [], [['text', '/homepage']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginFormController::new'], [], [['text', '/login']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\LogoutController::logout'], [], [['text', '/logout']], [], [], []],
    'material' => [[], ['_controller' => 'App\\Controller\\MaterialFormController::material'], [], [['text', '/material']], [], [], []],
    'all_materials' => [[], ['_controller' => 'App\\Controller\\MaterialPageController::homepage'], [], [['text', '/all_materials']], [], [], []],
    'profile' => [['name'], ['_controller' => 'App\\Controller\\ProfileController::profile'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/profile']], [], [], []],
    'my_profile' => [[], ['_controller' => 'App\\Controller\\ProfileController::my_profile'], [], [['text', '/profile']], [], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\RegisterFormController::test'], [], [['text', '/register']], [], [], []],
    'settings' => [[], ['_controller' => 'App\\Controller\\SettingFormController::new'], [], [['text', '/settings']], [], [], []],
    'welcome_page' => [[], ['_controller' => 'App\\Controller\\WelcomePageController::homepage'], [], [['text', '/']], [], [], []],
];
